import { LessonContent } from '../types.js';
import { angularLabEnvironment } from './environments.js';

const start = 'npm install -g @angular/cli\nng new angular-lab --routing --style=css --ssr=false\ncd angular-lab\ncode .\nnpm start';

export const angularLessons: Record<string, LessonContent> = {
  'angular-intro': {
    centralQuestion: 'Que problemas aparecem quando uma interface cresce sem uma estrutura de aplicação?', prerequisites: ['HTML, CSS e TypeScript básico'],
    learningGoals: ['Explicar o papel de um framework', 'Reconhecer o mapa de recursos Angular', 'Separar conceito de prática'], misconceptions: ['Angular é uma biblioteca de CSS', 'É preciso decorar toda a API antes de criar algo'], skills: ['arquitetura mental'],
    environment: angularLabEnvironment(['Nenhum arquivo nesta aula conceitual'], '# Não crie o projeto ainda; apenas confirme a CLI\nng version', 'Você consegue apontar qual recurso Angular resolveria cada necessidade apresentada.'),
    sections: [
      { kind: 'comparison', title: 'DOM manual x aplicação organizada', items: ['Manual: localizar elementos e sincronizar estado por conta própria', 'Angular: componentes declaram partes da interface', 'Router associa URL e tela', 'Services + DI compartilham responsabilidades', 'Forms e HttpClient cobrem fluxos comuns'] },
      { kind: 'diagram', title: 'Mapa mental — sem aprofundar ainda', items: ['Componente ↔ template', 'Componente → service por DI', 'Router → componente da URL', 'Form → estado e validação', 'HttpClient → API'] },
      { kind: 'reflection', title: 'Escolha a ferramenta', prompt: 'Para trocar /produtos por /login, você pensa primeiro em component, router ou HttpClient?', answer: 'Router. As páginas ainda serão componentes, mas a escolha por URL é responsabilidade do roteamento.' }
    ], checklist: ['Explico por que usar framework', 'Associo recurso a problema', 'Sei que a Academy não é o Angular Lab'], resources: [{ title: 'Angular — What is Angular?', url: 'https://angular.dev/overview', source: 'Angular' }], connection: 'Na próxima aula, você cria o Angular Lab moderno e inspeciona sua anatomia.'
  },
  'angular-structure': {
    centralQuestion: 'Qual arquivo inicia, configura e apresenta uma aplicação Angular moderna?', prerequisites: ['Angular em visão geral', 'Terminal e npm'],
    learningGoals: ['Criar angular-lab standalone', 'Localizar arquivos reais da CLI atual', 'Executar o servidor local'], misconceptions: ['O código deve ser criado dentro da Academy', 'Todo projeto Angular moderno tem app.module.ts'], skills: ['Angular CLI', 'workspace'],
    environment: angularLabEnvironment(['angular.json', 'package.json', 'src/main.ts', 'src/app/app.ts', 'src/app/app.html', 'src/app/app.config.ts', 'src/app/app.routes.ts'], start, 'Angular Lab abre em localhost:4200 e cada arquivo do mapa é localizado no Explorer.'),
    sections: [
      { kind: 'lab', title: 'Crie o laboratório contínuo', steps: ['Execute os comandos na pasta meus-estudos, fora da Academy.', 'Aceite standalone (padrão), routing ativado, CSS e sem SSR.', 'A CLI atual pode perguntar sobre IA; escolha none se não quiser arquivos adicionais.', 'Mantenha Vitest, o runner padrão atual.'] },
      { kind: 'diagram', title: 'Anatomia real da CLI atual', items: ['angular.json → workspace e tarefas', 'package.json → dependências e scripts', 'src/main.ts → bootstrapApplication', 'app.config.ts → providers globais', 'app.routes.ts → URLs', 'app.ts + app.html + app.css → componente raiz'] },
      { kind: 'debugging', title: 'Procurando app.component.ts', prompt: 'A CLI criou app.ts. Algo deu errado?', solution: 'Não. O style guide 2025 usa nomes concisos por padrão. app.component.ts é o estilo legado 2016.', explanation: 'Siga os arquivos realmente gerados no seu projeto.' }
    ], checklist: ['Angular Lab está fora da Academy', 'Localizo bootstrap e rotas', 'Reconheço nomes 2025'], resources: [{ title: 'Angular — Installation', url: 'https://angular.dev/installation', source: 'Angular' }, { title: 'Angular CLI — ng new', url: 'https://angular.dev/cli/new', source: 'Angular' }], connection: 'O laboratório criado receberá o primeiro componente visual do catálogo.'
  },
  components: {
    centralQuestion: 'Como encapsular uma parte visual com marcação, estilo e comportamento próprios?', prerequisites: ['Angular Lab criado', 'Anatomia do workspace'],
    learningGoals: ['Gerar perfil-card', 'Ler metadata de @Component', 'Compor componente standalone'], misconceptions: ['Selector adiciona o componente sozinho à tela', 'Estilo do componente é global por padrão'], skills: ['components', 'CLI'],
    environment: angularLabEnvironment(['src/app/components/perfil-card/perfil-card.ts', 'perfil-card.html', 'perfil-card.css', 'src/app/app.ts', 'src/app/app.html'], 'cd angular-lab\nng generate component components/perfil-card\nnpm start', 'Um card de perfil estilizado aparece na tela inicial.'),
    sections: [
      { kind: 'lab', title: 'Leia os arquivos gerados antes de editar', steps: ['Abra perfil-card.ts e identifique selector, templateUrl e styleUrl.', 'No HTML, crie foto com alt, nome e função.', 'No CSS, limite largura e defina foco/contraste.', 'Importe PerfilCard em app.ts.', 'Use <app-perfil-card /> em app.html.'] },
      { kind: 'code', title: 'Metadata conecta as três partes', code: "@Component({\n  selector: 'app-perfil-card',\n  imports: [],\n  templateUrl: './perfil-card.html',\n  styleUrl: './perfil-card.css'\n})\nexport class PerfilCard {}", language: 'ts', explanation: 'A classe contém comportamento; selector identifica o host; URLs são relativas ao arquivo TypeScript.' },
      { kind: 'debugging', title: 'Unknown element', prompt: 'app.html usa <app-perfil-card>, mas o compilador diz que o elemento não é conhecido.', solution: 'Importe PerfilCard e inclua a classe em imports do @Component raiz.', explanation: 'Componentes standalone declaram explicitamente suas dependências.' }
    ], checklist: ['Gero e localizo o componente', 'Explico metadata', 'Importo componente standalone no pai'], resources: [{ title: 'Angular — Anatomy of components', url: 'https://angular.dev/guide/components', source: 'Angular' }], connection: 'O card passará a receber dados do catálogo e emitir eventos.'
  },
  'inputs-outputs': {
    centralQuestion: 'Como pai e filho trocam dados sem disputar a propriedade do estado?', prerequisites: ['PerfilCard existente', 'Componentes standalone'],
    learningGoals: ['Usar input() e output()', 'Desenhar fluxo pai-filho', 'Emitir evento sem alterar estado externo'], misconceptions: ['Output envia dados do pai ao filho', 'Filho deve editar diretamente a lista do pai'], skills: ['comunicação de componentes'],
    environment: angularLabEnvironment(['src/app/components/perfil-card/perfil-card.ts', 'perfil-card.html', 'src/app/app.ts', 'src/app/app.html'], 'cd angular-lab\nnpm start', 'O pai envia o perfil; clicar no filho faz o pai registrar o id selecionado.'),
    sections: [
      { kind: 'diagram', title: 'O sentido das setas', items: ['PAI — [perfil] → FILHO', 'FILHO — (selecionar) → PAI', 'Estado permanece no dono; evento comunica intenção'] },
      { kind: 'code', title: 'API moderna no filho', code: "perfil = input.required<Perfil>();\nselecionar = output<number>();\n\n// template\n<button (click)=\"selecionar.emit(perfil().id)\">Selecionar</button>", language: 'ts', explanation: 'Signal input é lido com perfil(); output possui emit().' },
      { kind: 'debugging', title: 'Binding invertido', code: '<app-perfil-card (perfil)="pessoa" [selecionar]="aoSelecionar($event)" />', language: 'html', prompt: 'Quais símbolos estão trocados?', solution: '<app-perfil-card [perfil]="pessoa" (selecionar)="aoSelecionar($event)" />', explanation: 'Colchetes entregam valor; parênteses escutam evento.' }
    ], checklist: ['Desenho as duas direções', 'Leio input signal corretamente', 'Emito intenção e deixo o pai decidir'], resources: [{ title: 'Angular — Inputs', url: 'https://angular.dev/guide/components/inputs', source: 'Angular' }, { title: 'Angular — Outputs', url: 'https://angular.dev/guide/components/outputs', source: 'Angular' }], connection: 'O projeto Card de Produto aplicará esse fluxo em uma entrega completa.'
  },
  'product-project': {
    centralQuestion: 'Como transformar um contrato de produto em um componente reutilizável, acessível e observável?', prerequisites: ['Componentes', 'input()', 'output()'], learningGoals: ['Construir card completo', 'Tratar estoque e evento', 'Verificar acessibilidade básica'], misconceptions: ['Projeto é repetir a aula anterior', 'Imagem decorativa sempre dispensa alt'], skills: ['projeto incremental', 'acessibilidade'],
    environment: angularLabEnvironment(['src/app/models/produto.ts', 'src/app/components/produto-card/*', 'src/app/app.ts', 'src/app/app.html'], 'cd angular-lab\nng generate interface models/produto\nng generate component components/produto-card\nnpm start', 'Três produtos renderizam nome, preço, estoque e botão; o clique informa o produto ao pai.'),
    sections: [
      { kind: 'milestones', title: 'Entrega em camadas', items: ['1. Produto: id, nome, preco, imagemUrl, estoque', '2. Card recebe produto', '3. Template exibe imagem e moeda', '4. Botão desabilita sem estoque', '5. Output adicionar envia o produto', '6. Teclado e leitor de tela recebem nome acessível'] },
      { kind: 'practice', title: 'Critérios de aceite', prompt: 'Implemente sem copiar um card pronto. Teste um produto disponível e outro esgotado.', solution: 'Disponível: botão acionável emite o id. Esgotado: texto explícito e botão disabled. A imagem possui alt derivado do nome.', explanation: 'Os critérios permitem várias soluções visuais, mas tornam o comportamento verificável.' },
      { kind: 'debugging', title: 'Preço concatenado', prompt: 'O template mostra R$ 199.9 sem formatação. Onde resolver?', solution: 'Use CurrencyPipe no componente standalone e {{ produto().preco | currency:"BRL" }}.', explanation: 'Pipe formata apresentação sem alterar o valor numérico do modelo.' }
    ], checklist: ['Card atende os seis critérios', 'Estado esgotado é compreensível', 'Evento chega ao pai', 'Teste por teclado realizado'], resources: [{ title: 'Angular — Accessibility', url: 'https://angular.dev/best-practices/a11y', source: 'Angular' }], connection: 'Data binding explicará formalmente as quatro conexões usadas no card.'
  },
  binding: {
    centralQuestion: 'Qual sintaxe conecta estado e template em cada direção?', prerequisites: ['Componente e template', 'Eventos DOM'], learningGoals: ['Comparar quatro bindings', 'Escolher direção correta', 'Usar FormsModule somente para two-way binding'], misconceptions: ['Interpolação serve para qualquer propriedade', '[click] registra evento'], skills: ['template binding'],
    environment: angularLabEnvironment(['src/app/components/binding-lab/binding-lab.ts', 'binding-lab.html'], 'cd angular-lab\nng generate component components/binding-lab\nnpm start', 'Um único laboratório demonstra TS→HTML, HTML→TS e TS↔HTML.'),
    sections: [
      { kind: 'comparison', title: 'Quatro técnicas, três direções', items: ['{{ nome }} → texto TS para HTML', '[disabled]="salvando" → propriedade TS para DOM', '(click)="salvar()" → evento DOM para TS', '[(ngModel)]="busca" → sincronização em duas direções'] },
      { kind: 'code', title: 'Mesmo componente, técnicas diferentes', code: '<h2>{{ titulo }}</h2>\n<button [disabled]="ocupado" (click)="alternar()">Alternar</button>\n<input [(ngModel)]="termo">\n<p>Busca: {{ termo }}</p>', language: 'html', explanation: 'ngModel exige FormsModule em imports; os outros bindings não.' },
      { kind: 'debugging', title: 'Evento como propriedade', code: '<button [click]="salvar()">Salvar</button>', language: 'html', prompt: 'Qual é a correção?', solution: '<button (click)="salvar()">Salvar</button>', explanation: 'click é evento, por isso usa parênteses.' }
    ], checklist: ['Escolho a sintaxe pela direção', 'Não confundo property e event binding', 'Importo FormsModule para ngModel'], resources: [{ title: 'Angular — Binding dynamic properties and attributes', url: 'https://angular.dev/guide/templates/binding', source: 'Angular' }, { title: 'Angular — Two-way binding', url: 'https://angular.dev/guide/templates/two-way-binding', source: 'Angular' }], connection: 'Controle de fluxo decidirá quais blocos aparecem para cada estado.'
  },
  'control-flow': {
    centralQuestion: 'Como o template representa loading, vazio, erro e sucesso sem lógica duplicada?', prerequisites: ['Binding', 'Arrays', 'ProdutoCard'], learningGoals: ['Aplicar @if, @else e @for', 'Escolher track estável', 'Reconhecer @switch'], misconceptions: ['track $index é sempre ideal', 'Diretivas modernas exigem CommonModule'], skills: ['controle de fluxo', 'estados de UI'],
    environment: angularLabEnvironment(['src/app/app.ts', 'src/app/app.html'], 'cd angular-lab\nnpm start', 'A tela troca corretamente entre loading, erro, vazio e catálogo com cards.'),
    sections: [
      { kind: 'diagram', title: 'Máquina de estados da tela', items: ['carregando → indicador', 'erro → mensagem + tentar novamente', 'sucesso vazio → orientação', 'sucesso com dados → lista'] },
      { kind: 'code', title: 'Fluxo moderno', code: '@if (carregando()) { <p>Carregando…</p> }\n@else if (erro()) { <p role="alert">{{ erro() }}</p> }\n@else {\n  @for (produto of produtos(); track produto.id) { <app-produto-card [produto]="produto" /> }\n  @empty { <p>Nenhum produto cadastrado.</p> }\n}', language: 'html', explanation: 'track por id preserva a identidade quando a lista muda; @empty pertence ao @for.' },
      { kind: 'prediction', title: 'Qual estado vence?', prompt: 'Se carregando for true e produtos já tiver itens antigos, o que aparece?', answer: 'O primeiro ramo: carregando. A ordem explicita a prioridade visual.' }
    ], checklist: ['Represento quatro estados', 'Uso track estável', 'Sei quando @switch torna estados exclusivos mais claros'], resources: [{ title: 'Angular — Control flow', url: 'https://angular.dev/guide/templates/control-flow', source: 'Angular' }], connection: 'O service retirará regras e dados duplicados dos componentes.'
  },
  services: {
    centralQuestion: 'Quem concentra uma responsabilidade compartilhada e quem cria sua instância?', prerequisites: ['Componentes', 'inject()', 'Catálogo'], learningGoals: ['Separar service de DI', 'Gerar CatalogoService', 'Injetar sem new'], misconceptions: ['Service e DI são sinônimos', 'Service existe apenas para HTTP'], skills: ['services', 'dependency injection'],
    environment: angularLabEnvironment(['src/app/services/catalogo.ts', 'src/app/app.ts'], 'cd angular-lab\nng generate service services/catalogo\nnpm start', 'Dois componentes leem a mesma fonte do catálogo sem duplicar a lista.'),
    sections: [
      { kind: 'diagram', title: 'Da duplicação à centralização', items: ['Home mantém cópia A', 'Busca mantém cópia B', 'Carrinho mantém regra C', 'Refatoração: CatalogoService concentra estado/regras', 'Injector entrega a instância aos consumidores'] },
      { kind: 'comparison', title: 'Service ≠ Dependency Injection', items: ['Service: classe com responsabilidade', 'DI: mecanismo que cria e fornece dependências', '@Injectable({ providedIn: "root" }): configuração de disponibilidade', 'inject(CatalogoService): pedido ao injector'] },
      { kind: 'code', title: 'Estado compartilhado pequeno', code: "@Injectable({ providedIn: 'root' })\nexport class CatalogoService {\n  readonly produtos = signal<Produto[]>([]);\n}\n\nprivate catalogo = inject(CatalogoService);", language: 'ts', explanation: 'O componente não usa new; Angular controla o ciclo da instância.' },
      { kind: 'debugging', title: 'Instância paralela', prompt: 'Por que new CatalogoService() dentro do componente é inadequado?', solution: 'Use inject(CatalogoService). new ignora o injector e pode criar estado separado, além de dificultar substituição em testes.', explanation: 'DI conecta consumidor e implementação.' }
    ], checklist: ['Explico service separadamente de DI', 'Uso inject()', 'Centralizo uma responsabilidade concreta'], resources: [{ title: 'Angular — Creating and using services', url: 'https://angular.dev/guide/di/creating-injectable-service', source: 'Angular' }, { title: 'Angular — Dependency injection', url: 'https://angular.dev/guide/di', source: 'Angular' }], connection: 'Routing organizará o catálogo em páginas endereçáveis.'
  },
  routing: {
    centralQuestion: 'Como uma URL escolhe a tela certa e carrega apenas o necessário?', prerequisites: ['Componentes standalone', 'Services'], learningGoals: ['Definir rotas progressivamente', 'Usar outlet, links e params', 'Adicionar 404, guard e lazy loading'], misconceptions: ['Guard protege dados no servidor', 'href e routerLink sempre têm o mesmo efeito'], skills: ['routing', 'lazy loading'],
    environment: angularLabEnvironment(['src/app/app.routes.ts', 'src/app/app.html', 'src/app/pages/*', 'src/app/guards/auth.ts'], 'cd angular-lab\nng generate component pages/inicio\nng generate component pages/produtos\nng generate component pages/produto-detalhe\nng generate component pages/login\nng generate component pages/dashboard\nng generate component pages/nao-encontrado\nng generate guard guards/auth\nnpm start', 'Todas as URLs do mapa funcionam; id é lido; rota desconhecida mostra 404; dashboard é lazy.'),
    sections: [
      { kind: 'diagram', title: 'Mapa de URLs', items: ['/ → Início', '/produtos → lista', '/produtos/:id → detalhe', '/login → login', '/dashboard → lazy + guard', '/** → 404 (wildcard por último)'] },
      { kind: 'milestones', title: 'Configure e teste uma camada por vez', items: ['1. routes + provideRouter já criado pela CLI', '2. <router-outlet /> no app.html', '3. routerLink no menu', '4. parâmetro :id', '5. wildcard ** por último', '6. CanActivateFn', '7. loadComponent para dashboard'] },
      { kind: 'code', title: 'Lazy route moderna', code: "{ path: 'dashboard', canActivate: [authGuard], loadComponent: () =>\n  import('./pages/dashboard/dashboard').then(m => m.Dashboard)\n}", language: 'ts', explanation: 'loadComponent permite separar o bundle da página standalone.' },
      { kind: 'debugging', title: 'Wildcard no topo', prompt: 'Todas as URLs mostram 404. Qual ordem revisar?', solution: 'Mova { path: "**", ... } para o fim. O router usa a primeira rota compatível.', explanation: 'A ordem é parte da configuração.' }
    ], checklist: ['Crio rota e link', 'Explico outlet', 'Leio parâmetro', 'Posiciono 404', 'Uso lazy sem confundir guard com segurança'], resources: [{ title: 'Angular — Define routes', url: 'https://angular.dev/guide/routing/define-routes', source: 'Angular' }, { title: 'Angular — Route guards', url: 'https://angular.dev/guide/routing/route-guards', source: 'Angular' }], connection: 'Reactive Forms construirá a tela de cadastro do painel.'
  },
  forms: {
    centralQuestion: 'Como representar valores, validação e interação de um formulário como estado testável?', prerequisites: ['Binding', 'Componentes standalone'], learningGoals: ['Construir FormGroup', 'Exibir erros após interação', 'Relacionar validação e acessibilidade'], misconceptions: ['invalid significa que a mensagem deve aparecer imediatamente', 'Validação no navegador substitui backend'], skills: ['Reactive Forms', 'a11y'],
    environment: angularLabEnvironment(['src/app/pages/cadastro/cadastro.ts', 'cadastro.html'], 'cd angular-lab\nng generate component pages/cadastro\nnpm start', 'O formulário bloqueia envio inválido, explica os erros e aceita dados válidos.'),
    sections: [
      { kind: 'comparison', title: 'HTML simples x modelo reativo', items: ['HTML: constraints básicas no elemento', 'FormControl: valor e estado de um campo', 'FormGroup: estrutura do formulário', 'Validators: regras combináveis', 'FormBuilder: construção menos repetitiva'] },
      { kind: 'code', title: 'Modelo no TypeScript', code: "private fb = inject(FormBuilder);\nform = this.fb.nonNullable.group({\n  nome: ['', [Validators.required, Validators.minLength(3)]],\n  email: ['', [Validators.required, Validators.email]],\n});", language: 'ts', explanation: 'nonNullable evita null no valor; ReactiveFormsModule deve estar nos imports do componente.' },
      { kind: 'debugging', title: 'Erro gritando cedo demais', prompt: 'A mensagem aparece antes de a pessoa tocar no campo. Qual condição melhora a experiência?', solution: '@if (form.controls.email.invalid && form.controls.email.touched) { ... }', explanation: 'invalid descreve regra; touched/dirty descrevem interação.' },
      { kind: 'deep-dive', title: 'Conheça também: Signal Forms', body: 'A documentação atual apresenta Signal Forms como experimental. Observe a evolução, mas mantenha Reactive Forms como base estável desta trilha.' }
    ], checklist: ['Importo ReactiveFormsModule', 'Diferencio valid de touched', 'Associo label e mensagem ao input', 'Backend continuará validando'], resources: [{ title: 'Angular — Reactive forms', url: 'https://angular.dev/guide/forms/reactive-forms', source: 'Angular' }, { title: 'Angular — Validating form input', url: 'https://angular.dev/guide/forms/form-validation', source: 'Angular' }], connection: 'HttpClient enviará e buscará dados desse painel.'
  },
  http: {
    centralQuestion: 'Como transformar uma conversa HTTP em estados confiáveis de interface?', prerequisites: ['HTTP básico', 'Services', 'RxJS introdutório será aprofundado depois'], learningGoals: ['Configurar provideHttpClient', 'Implementar GET e CRUD em service', 'Exibir loading, erro e vazio'], misconceptions: ['HttpClient faz a requisição sem subscription/consumo', 'CORS se corrige no template'], skills: ['HttpClient', 'CRUD', 'Network'],
    environment: angularLabEnvironment(['src/app/app.config.ts', 'src/app/services/produtos-api.ts', 'src/app/pages/produtos/*'], 'cd angular-lab\nng generate service services/produtos-api\nnpm start', 'Network mostra a requisição; a tela apresenta loading, sucesso/vazio ou erro de modo exclusivo.'),
    sections: [
      { kind: 'retrieval', title: 'Volte à primeira aula', prompt: 'Na aba Network, quais três dados ajudam a diagnosticar uma chamada?', answer: 'Method, Status e Response; headers e timing ajudam no aprofundamento.' },
      { kind: 'comparison', title: 'Verbos do CRUD', items: ['GET → ler', 'POST → criar', 'PUT/PATCH → substituir/alterar', 'DELETE → remover', '2xx → sucesso; 4xx → pedido/cliente; 5xx → servidor'] },
      { kind: 'code', title: 'Configuração moderna e service', code: "// app.config.ts\nproviders: [provideHttpClient(withInterceptors([authInterceptor]))]\n\n// service\nprivate http = inject(HttpClient);\nlistar() { return this.http.get<Produto[]>('/api/produtos'); }", language: 'ts', explanation: 'provideHttpClient substitui a configuração por módulo; interceptor funcional fica explícito.' },
      { kind: 'lab', title: 'Observe antes de completar o CRUD', steps: ['Implemente somente GET.', 'Abra Network e confirme URL/status.', 'Modele loading/error/empty/success.', 'Adicione POST e teste payload.', 'Depois PATCH e DELETE.', 'Teste uma URL inválida para observar erro.'] },
      { kind: 'debugging', title: 'Erro de CORS', prompt: 'O console bloqueia a resposta por CORS. Deve-se adicionar um header no template?', solution: 'Não. Configure a API/proxy corretamente; CORS é uma política entre origens aplicada pelo navegador.', explanation: 'O componente não pode conceder permissão em nome do servidor.' }
    ], checklist: ['Configuro provideHttpClient', 'Vejo request no Network', 'Represento quatro estados', 'Não uso any na resposta'], resources: [{ title: 'Angular — Setting up HttpClient', url: 'https://angular.dev/guide/http/setup', source: 'Angular' }, { title: 'Angular — Making requests', url: 'https://angular.dev/guide/http/making-requests', source: 'Angular' }], connection: 'RxJS explicará o fluxo retornado pelo HttpClient e a busca digitada.'
  },
  rxjs: {
    centralQuestion: 'Como tratar uma sequência de valores que chega ao longo do tempo?', prerequisites: ['Funções', 'HTTP', 'Eventos de formulário'], learningGoals: ['Ler Observable e subscribe', 'Compor operadores', 'Escolher switchMap em busca cancelável'], misconceptions: ['Observable é Promise com outro nome', 'switchMap mantém todas as requisições'], skills: ['RxJS', 'streams'],
    environment: angularLabEnvironment(['src/app/pages/produtos/produtos.ts', 'produtos.html'], 'cd angular-lab\nnpm start', 'A busca aguarda digitação, descarta consultas antigas e trata falha sem quebrar o fluxo.'),
    sections: [
      { kind: 'timeline', title: 'Valores no tempo', items: ['teclas: a ─ an ─ ang ─ angu', 'debounceTime: espera pausa', 'distinctUntilChanged: ignora repetição', 'switchMap: troca busca antiga pela nova', 'catchError: converte falha em estado recuperável'] },
      { kind: 'code', title: 'Da fonte ao resultado', code: "resultados$ = this.termo.valueChanges.pipe(\n  debounceTime(300),\n  distinctUntilChanged(),\n  switchMap(termo => this.api.buscar(termo)),\n  catchError(() => of([]))\n);", language: 'ts', explanation: 'pipe descreve a transformação; async pipe no template gerencia a subscription visual.' },
      { kind: 'comparison', title: 'switchMap x mergeMap', items: ['switchMap → interessa apenas o resultado mais recente, como busca', 'mergeMap → todos os trabalhos precisam terminar, como uploads independentes', 'A escolha expressa semântica, não preferência pessoal'] },
      { kind: 'prediction', title: 'Usuário digita rápido', prompt: 'A busca por “an” demora mais que “angular”. Com switchMap, qual resultado permanece?', answer: 'O de “angular”. A subscription anterior é cancelada; a resposta obsoleta não domina a tela.' }
    ], checklist: ['Desenho stream no tempo', 'Explico pipe e subscribe', 'Escolho operador pela concorrência', 'Trato erro dentro do fluxo'], resources: [{ title: 'Angular — RxJS interop', url: 'https://angular.dev/ecosystem/rxjs-interop', source: 'Angular' }], connection: 'Signals oferecerão uma ferramenta complementar para estado local e derivado.'
  },
  signals: {
    centralQuestion: 'Como representar estado local reativo e valores derivados?', prerequisites: ['Componentes', 'RxJS'], learningGoals: ['Usar signal, set e update', 'Derivar com computed', 'Reservar effect para efeitos colaterais'], misconceptions: ['computed deve alterar outros signals', 'Signal substitui todo Observable'], skills: ['Signals', 'estado derivado'],
    environment: angularLabEnvironment(['src/app/pages/dashboard/dashboard.ts', 'dashboard.html'], 'cd angular-lab\nnpm start', 'Contador e total derivado atualizam; nenhum valor derivado é sincronizado manualmente.'),
    sections: [
      { kind: 'prediction', title: 'Prediga a derivação', code: 'quantidade = signal(2);\npreco = signal(15);\ntotal = computed(() => this.quantidade() * this.preco());\nthis.quantidade.update(q => q + 1);', language: 'ts', prompt: 'Quanto vale total() ao final?', answer: '45. computed relê as dependências quando quantidade muda.' },
      { kind: 'comparison', title: 'Escolha pela natureza do dado', items: ['estado local gravável → signal', 'estado derivado → computed', 'efeito colateral necessário → effect com cuidado', 'eventos/HTTP/concorrência → Observable costuma expressar melhor', 'ponte entre ambos → rxjs-interop'] },
      { kind: 'debugging', title: 'Duas fontes de verdade', prompt: 'O código mantém subtotal signal e também computed total com a mesma conta. Qual remover?', solution: 'Remova o signal gravável duplicado e mantenha computed como única derivação.', explanation: 'Estado derivado não deve exigir sincronização manual.' },
      { kind: 'deep-dive', title: 'effect não é calculadora', body: 'Use effect para sincronizar com algo externo, como logging ou storage. Para calcular valores usados no template, prefira computed.' }
    ], checklist: ['Leio signal com ()', 'Escolho set ou update', 'Derivo com computed', 'Não trato Signal e Observable como rivais universais'], resources: [{ title: 'Angular — Signals', url: 'https://angular.dev/guide/signals', source: 'Angular' }, { title: 'Angular — RxJS interop with signals', url: 'https://angular.dev/ecosystem/rxjs-interop', source: 'Angular' }], connection: 'Lifecycle explicará quando recursos ligados ao componente existem e são liberados.'
  },
  lifecycle: {
    centralQuestion: 'Em que momentos um componente pode iniciar, reagir e liberar trabalho?', prerequisites: ['Componentes', 'Signals', 'Subscriptions'], learningGoals: ['Reconhecer hooks essenciais', 'Usar DestroyRef para limpeza', 'Separar lifecycle de formatação por pipes'], misconceptions: ['ngDoCheck é lugar para qualquer cálculo', 'Toda subscription precisa de unsubscribe manual'], skills: ['lifecycle', 'cleanup'],
    environment: angularLabEnvironment(['src/app/components/relogio/relogio.ts'], 'cd angular-lab\nng generate component components/relogio\nnpm start', 'O relógio inicia ao entrar na tela e para sem vazamento ao sair.'),
    sections: [
      { kind: 'timeline', title: 'Vida do componente', items: ['constructor/injection context', 'inputs definidos', 'ngOnInit', 'renderizações e mudanças', 'ngOnDestroy / DestroyRef'] },
      { kind: 'code', title: 'Limpeza vinculada à destruição', code: "private destroyRef = inject(DestroyRef);\nngOnInit() {\n  const id = setInterval(() => this.agora.set(new Date()), 1000);\n  this.destroyRef.onDestroy(() => clearInterval(id));\n}", language: 'ts', explanation: 'O callback é registrado perto da criação do recurso, reduzindo chance de esquecimento.' },
      { kind: 'debugging', title: 'Intervalo fantasma', prompt: 'Ao sair e voltar à rota, logs aparecem duas vezes, depois três. Qual causa provável?', solution: 'Um interval ou subscription continua ativo após destruir o componente. Registre cleanup com DestroyRef ou use takeUntilDestroyed.', explanation: 'O sintoma cresce a cada nova instância.' },
      { kind: 'deep-dive', title: 'Pipes pertencem à apresentação', body: 'DatePipe transforma o valor exibido; ele não controla o lifecycle. Use {{ agora() | date:"mediumTime" }} e importe DatePipe no componente standalone.' }
    ], checklist: ['Identifico criação e destruição', 'Libero recurso criado', 'Evito trabalho pesado em hooks frequentes', 'Uso pipe para apresentação'], resources: [{ title: 'Angular — Component lifecycle', url: 'https://angular.dev/guide/components/lifecycle', source: 'Angular' }, { title: 'Angular — Pipes', url: 'https://angular.dev/guide/templates/pipes', source: 'Angular' }], connection: 'Arquitetura decidirá onde cada artefato do painel deve viver.'
  },
  architecture: {
    centralQuestion: 'Que vizinhança de arquivos torna uma mudança fácil de localizar e limitar?', prerequisites: ['Components', 'Services', 'Routing', 'HTTP'], learningGoals: ['Refatorar por feature', 'Explicar core/shared/layouts', 'Justificar cada movimento'], misconceptions: ['Arquitetura é copiar uma árvore de pastas', 'shared recebe tudo que não tem lugar'], skills: ['arquitetura feature-based', 'refatoração'],
    environment: angularLabEnvironment(['src/app/features/', 'src/app/core/', 'src/app/shared/', 'src/app/layouts/'], 'cd angular-lab\nnpm start', 'Rotas continuam funcionando após mover arquivos e cada pasta tem responsabilidade explicável.'),
    sections: [
      { kind: 'debugging', title: 'Comece pelo projeto bagunçado', body: 'app/ contém vinte componentes, cinco services e modelos sem agrupamento. Alterar produtos exige saltar por toda a árvore.', prompt: 'Quais arquivos mudam juntos?', solution: 'Agrupe páginas, componentes, modelos e acesso a dados de produtos em features/produtos.', explanation: 'Coesão orienta a pasta; não o tipo isolado do arquivo.' },
      { kind: 'comparison', title: 'Quatro destinos com motivo', items: ['features/produtos → regra e UI específicas de produtos', 'core → infraestrutura única da aplicação, como sessão', 'shared → componente/pipeline genérico sem regra de negócio', 'layouts → cascas de navegação para grupos de páginas'] },
      { kind: 'practice', title: 'Classifique e justifique', prompt: 'Mova auth interceptor, botão genérico, ProdutosPage e AdminLayout. Para cada um escreva “pertence aqui porque…”.', solution: 'core/interceptors; shared/ui; features/produtos/pages; layouts/admin. Revise se algum item importa uma feature concreta de forma invertida.', explanation: 'A justificativa vale mais que a pasta em si.' }
    ], checklist: ['Agrupo por mudança conjunta', 'Não uso shared como depósito', 'Rotas passam após refatoração', 'Justifico cada fronteira'], resources: [{ title: 'Angular — Style guide: project structure', url: 'https://angular.dev/style-guide#project-structure', source: 'Angular' }], connection: 'Autenticação atravessará core, rotas e comunicação HTTP.'
  },
  auth: {
    centralQuestion: 'Como manter sessão e experiência de acesso sem fingir que o navegador é a fronteira de segurança?', prerequisites: ['Routing guards', 'HTTP interceptors', 'Services'], learningGoals: ['Separar autenticação de autorização', 'Desenhar fluxo com backend', 'Implementar guard/interceptor funcionais'], misconceptions: ['Guard protege a API', 'Guardar token garante autorização'], skills: ['auth flow', 'segurança conceitual'],
    environment: angularLabEnvironment(['src/app/core/auth/auth.ts', 'src/app/core/auth/auth.guard.ts', 'src/app/core/http/auth.interceptor.ts'], 'cd angular-lab\nng generate service core/auth/auth\nng generate guard core/auth/auth\nng generate interceptor core/http/auth\nnpm start', 'Sem sessão, dashboard redireciona; requests autorizados recebem credencial; backend continua sendo responsável por validar.'),
    sections: [
      { kind: 'comparison', title: 'Termos que não são sinônimos', items: ['login → coleta credenciais', 'autenticação → confirma identidade', 'sessão/token → representa continuidade', 'autorização → decide permissão', 'guard → controla navegação', 'backend → valida de verdade'] },
      { kind: 'diagram', title: 'Fluxo completo', items: ['Login envia credenciais → API', 'API valida → cria sessão/token', 'Cliente envia credencial → request', 'Backend valida identidade e permissão', 'Resposta autorizada ou 401/403'] },
      { kind: 'code', title: 'Guard funcional para experiência', code: "export const authGuard: CanActivateFn = () => {\n  const auth = inject(AuthService);\n  const router = inject(Router);\n  return auth.autenticado() || router.createUrlTree(['/login']);\n};", language: 'ts', explanation: 'O guard evita mostrar a rota, mas uma chamada direta à API ainda deve ser recusada pelo servidor.' },
      { kind: 'debugging', title: 'Falsa segurança', prompt: 'A API entrega /admin para qualquer request, mas o botão está oculto e há guard. Está protegido?', solution: 'Não. O backend precisa autenticar e autorizar cada operação sensível.', explanation: 'Código do navegador pode ser inspecionado e requests podem ser feitos fora da interface.' }
    ], checklist: ['Diferencio autenticação e autorização', 'Explico limite do guard', 'Interceptor não decide permissão', 'Backend valida ações'], resources: [{ title: 'Angular — Route guards: critical note', url: 'https://angular.dev/guide/routing/route-guards#control-route-access-with-guards', source: 'Angular' }, { title: 'Angular — Interceptors', url: 'https://angular.dev/guide/http/interceptors', source: 'Angular' }], connection: 'Qualidade verificará desempenho, comportamento e clareza antes da entrega final.'
  },
  quality: {
    centralQuestion: 'Como obter evidência de que a aplicação continua rápida, correta e compreensível?', prerequisites: ['Projeto Angular funcional', 'Arquitetura', 'HTTP'], learningGoals: ['Separar performance, teste e review', 'Escrever teste que falha e passa', 'Usar Vitest conforme CLI atual'], misconceptions: ['Teste que passa prova ausência de bugs', 'Otimização começa com microajustes'], skills: ['performance', 'Vitest', 'code review'],
    environment: angularLabEnvironment(['src/app/**/*.spec.ts', 'angular.json', 'package.json'], 'cd angular-lab\nnpm test\nng build', 'Um teste falha pela razão prevista, passa após a correção e o build de produção conclui.'),
    sections: [
      { kind: 'comparison', title: 'Três perguntas diferentes', items: ['Performance: fazemos trabalho ou carregamento desnecessário?', 'Teste: o comportamento observável continua correto?', 'Code review: a mudança é segura, legível e acessível?'] },
      { kind: 'lab', title: 'Vermelho → verde → revisão', steps: ['Escreva expect(calcularTotal(...)).toBe(40) antes da função.', 'Execute npm test e confirme falha relevante.', 'Implemente o mínimo para passar.', 'Refatore nomes sem quebrar o teste.', 'Revise foco, labels, estados e imports lazy.'] },
      { kind: 'code', title: 'Vitest na CLI atual', code: "import { describe, expect, it } from 'vitest';\ndescribe('calcularTotal', () => {\n  it('multiplica preço e quantidade', () => {\n    expect(calcularTotal(20, 2)).toBe(40);\n  });\n});", language: 'ts', explanation: 'Projetos novos selecionam Vitest por padrão; projetos antigos podem usar outra configuração, que deve ser respeitada durante migração.' },
      { kind: 'debugging', title: 'Teste acoplado ao detalhe', prompt: 'Um teste procura uma variável privada pelo nome. Que risco existe?', solution: 'Teste o resultado público ou a interface renderizada. Renomear implementação não deveria quebrar comportamento.', explanation: 'Testes frágeis impedem refatoração útil.' }
    ], checklist: ['Meço antes de otimizar', 'Vejo o teste falhar primeiro', 'Testo comportamento público', 'Review inclui acessibilidade'], resources: [{ title: 'Angular — Testing overview', url: 'https://angular.dev/guide/testing', source: 'Angular' }, { title: 'Angular — Performance best practices', url: 'https://angular.dev/best-practices/runtime-performance', source: 'Angular' }], connection: 'O projeto final reunirá evidências de todas essas competências.'
  },
  'final-project': {
    centralQuestion: 'Como planejar, construir, verificar e entregar um painel administrativo completo?', prerequisites: ['Todos os módulos Angular', 'Git básico'], learningGoals: ['Entregar por milestones', 'Integrar estados e segurança', 'Produzir evidências de qualidade'], misconceptions: ['Projeto final é colar snippets das aulas', 'Funcionar no caminho feliz encerra a entrega'], skills: ['integração', 'planejamento', 'portfólio'],
    environment: angularLabEnvironment(['README.md', 'src/app/features/', 'src/app/core/', 'src/app/shared/', 'src/app/**/*.spec.ts'], 'cd angular-lab\nnpm test\nng build\nnpm start', 'O briefing é atendido, testes e build passam, e a aplicação funciona por teclado e em viewport móvel.'),
    sections: [
      { kind: 'concept', title: 'Briefing', body: 'Crie um painel para administrar produtos: login, resumo, lista, detalhe, criação, edição e exclusão. A API pode ser simulada, mas os estados precisam ser reais e observáveis.' },
      { kind: 'milestones', title: 'Plano de entrega', items: ['1. Arquitetura + mapa de rotas', '2. Catálogo GET com loading/error/empty', '3. Formulário criar/editar acessível', '4. CRUD e confirmação de exclusão', '5. Sessão, guard e interceptor', '6. Signals para estado local + RxJS para busca/HTTP', '7. Testes, responsividade e revisão'] },
      { kind: 'practice', title: 'Definition of Done', prompt: 'Para cada milestone, registre URL, captura do resultado, caso de erro testado e teste automatizado relevante.', solution: 'A entrega inclui README com instalação, decisões, credenciais de demonstração, limitações e evidências. npm test e ng build devem passar.', explanation: 'Evidência torna a qualidade verificável por outra pessoa.' },
      { kind: 'reflection', title: 'Code review final', items: ['Rotas lazy onde ajudam', 'Sem any em respostas', 'Labels, foco e contraste', 'Backend tratado como fronteira de segurança', 'Erros úteis sem expor segredo', 'Mobile sem rolagem horizontal', 'Sem subscriptions ou timers abandonados'] }
    ], checklist: ['Briefing atendido', 'CRUD completo', 'Quatro estados de UI', 'Auth com limites explicados', 'Testes e build passam', 'A11y e mobile revisados', 'README permite reprodução'], resources: [{ title: 'Angular — Essentials', url: 'https://angular.dev/essentials', source: 'Angular' }, { title: 'Angular — Security', url: 'https://angular.dev/best-practices/security', source: 'Angular' }], connection: 'Você concluiu a trilha; use o relatório de decisões para orientar a próxima evolução do projeto.'
  }
};
