export interface DedicatedExample {
  minimum: string;
  real: string;
  exercise: string;
  result: string;
}

// Conteúdo explícito para as aulas que antes caíam em um exemplo padrão.
export const dedicatedExamples: Record<string, DedicatedExample> = {
  web: { minimum: `// HTML: estrutura\n<button id="comprar">Comprar</button>\n\n// JavaScript: comportamento\ndocument.querySelector('#comprar')?.addEventListener('click', () => {\n  console.log('Produto comprado');\n});`, real: `GET /produtos\n\n200 OK\n[\n  { "id": 1, "nome": "Notebook", "preco": 3500 }\n]`, exercise: `Crie um botão HTML com id="salvar" e mostre "Cadastro salvo" no console quando ele for clicado.`, result: 'Ao clicar no botão, o console mostra: Produto comprado.' },
  setup: { minimum: `node --version\nnpm --version`, real: `npm install\nnpm run dev`, exercise: `No terminal do VS Code, execute node --version e anote a versão exibida. Depois execute npm --version.`, result: 'O terminal mostra duas versões, por exemplo: v18.16.1 e 9.5.1.' },
  unions: { minimum: `type StatusPedido = 'aberto' | 'pago' | 'cancelado';\n\nlet status: StatusPedido = 'aberto';`, real: `function mostrarStatus(status: StatusPedido): string {\n  return status === 'pago' ? 'Pagamento confirmado' : 'Aguardando ação';\n}`, exercise: `Crie o tipo Nivel com as opções 'iniciante', 'intermediario' e 'avancado'. Depois declare uma variável nivel.`, result: 'status só pode receber aberto, pago ou cancelado.' },
  narrowing: { minimum: `function formatarCodigo(codigo: string | number): string {\n  if (typeof codigo === 'number') {\n    return codigo.toFixed(2);\n  }\n\n  return codigo.toUpperCase();\n}`, real: `const resposta: string | null = obterMensagem();\nif (resposta !== null) {\n  console.log(resposta.length);\n}`, exercise: `Crie uma função que receba string | number. Se for número, multiplique por 2; se for texto, transforme em maiúsculas.`, result: 'formatarCodigo(12) retorna 12.00; formatarCodigo("ab") retorna AB.' },
  'advanced-types': { minimum: `interface Usuario {\n  id: number;\n  nome: string;\n  email: string;\n}\n\ntype UsuarioPublico = Pick<Usuario, 'id' | 'nome'>;`, real: `type AtualizacaoUsuario = Partial<Usuario>;\n\nconst alteracao: AtualizacaoUsuario = { email: 'novo@email.com' };`, exercise: `Usando a interface Usuario, crie um tipo UsuarioSemEmail que remova a propriedade email.`, result: 'UsuarioPublico possui id e nome, mas não possui email.' },
  async: { minimum: `async function buscarLivro(): Promise<string> {\n  return 'Clean Code';\n}\n\nconst livro = await buscarLivro();\nconsole.log(livro);`, real: `async function carregarPerfil(): Promise<void> {\n  try {\n    const perfil = await api.buscarPerfil();\n    console.log(perfil.nome);\n  } catch {\n    console.log('Não foi possível carregar o perfil');\n  }\n}`, exercise: `Crie uma função async chamada carregarMensagem que retorne "Pronto" e use await para obter a mensagem.`, result: 'O console mostra: Clean Code.' },
  'todo-project': { minimum: `interface Tarefa {\n  titulo: string;\n  concluida: boolean;\n}\n\nconst tarefas: Tarefa[] = [\n  { titulo: 'Estudar TypeScript', concluida: false }\n];`, real: `function concluir(tarefa: Tarefa): Tarefa {\n  return { ...tarefa, concluida: true };\n}`, exercise: `Adicione uma tarefa chamada "Criar componente" à lista e marque-a como concluída usando uma função.`, result: 'A lista contém uma tarefa com concluida: false.' },
  'angular-intro': { minimum: `import { Component } from '@angular/core';\n\n@Component({\n  selector: 'app-raiz',\n  template: '<h1>Minha aplicação</h1>'\n})\nexport class AppComponent {}`, real: `Aplicação Angular\n├── HeaderComponent\n├── ProdutosComponent\n└── FooterComponent`, exercise: `Crie mentalmente três partes para uma tela de biblioteca: cabeçalho, lista de livros e rodapé. Dê um nome de componente para cada uma.`, result: 'O Angular renderiza o template do AppComponent na página.' },
  'angular-structure': { minimum: `src/\n├── main.ts\n└── app/\n    ├── app.component.ts\n    ├── app.component.html\n    └── app.routes.ts`, real: `// main.ts inicia a aplicação\nbootstrapApplication(AppComponent, appConfig);`, exercise: `No Explorer, localize main.ts, app.component.ts e app.routes.ts. Escreva em uma frase a responsabilidade de cada arquivo.`, result: 'main.ts inicia a aplicação; o componente define uma parte da tela; app.routes.ts define URLs.' },
  'product-project': { minimum: `export interface Produto {\n  nome: string;\n  preco: number;\n}\n\nconst item: Produto = { nome: 'Fone', preco: 120 };`, real: `<app-product-card\n  [produto]="item"\n  (adicionar)="colocarNoCarrinho($event)"\n/>`, exercise: `Crie um Produto chamado Livro com preço 45 e passe-o para um app-product-card.`, result: 'O card recebe um único produto e pode emitir um evento para o pai.' },
  'control-flow': { minimum: `@if (produtos.length === 0) {\n  <p>Nenhum produto encontrado.</p>\n} @else {\n  @for (produto of produtos; track produto.id) {\n    <p>{{ produto.nome }}</p>\n  }\n}`, real: `@for (curso of cursos; track curso.codigo) {\n  <app-curso-card [curso]="curso" />\n}`, exercise: `Crie uma lista de três tecnologias e use @for para mostrar cada tecnologia em um parágrafo.`, result: 'Com lista vazia aparece a mensagem; com itens aparece um parágrafo para cada produto.' },
  forms: { minimum: `form = this.formBuilder.group({\n  nome: ['', Validators.required],\n  email: ['', [Validators.required, Validators.email]],\n});`, real: `<input formControlName="email" aria-label="E-mail">\n@if (form.controls.email.invalid) {\n  <p>Informe um e-mail válido.</p>\n}`, exercise: `Crie um formulário com campo nome obrigatório. Mostre uma mensagem quando ele estiver vazio.`, result: 'Um e-mail inválido mantém o controle inválido; um e-mail válido remove o erro.' },
  lifecycle: { minimum: `ngOnInit(): void {\n  console.log('Componente criado e pronto para carregar dados');\n}\n\nngOnDestroy(): void {\n  console.log('Componente removido');\n}`, real: `@Pipe({ name: 'iniciais', standalone: true })\nexport class IniciaisPipe {\n  transform(nome: string): string {\n    return nome.split(' ').map(parte => parte[0]).join('');\n  }\n}`, exercise: `Adicione um console.log em ngOnInit e outro em ngOnDestroy. Navegue para outra página e observe o console.`, result: 'Ao criar o componente aparece a primeira mensagem; ao removê-lo aparece a segunda.' },
  architecture: { minimum: `src/app/\n├── core/\n│   └── services/\n├── shared/\n│   └── components/\n└── features/\n    └── produtos/`, real: `features/produtos/\n├── pages/lista-produtos/\n├── components/produto-card/\n└── services/produtos-api.service.ts`, exercise: `Organize mentalmente uma feature chamada cursos: escolha uma página, um componente reutilizável e um service.`, result: 'Arquivos de produtos ficam próximos, sem misturar regras de autenticação ou dashboard.' },
  auth: { minimum: `export const authGuard: CanActivateFn = () => {\n  const autenticado = Boolean(localStorage.getItem('token'));\n  return autenticado || inject(Router).createUrlTree(['/login']);\n};`, real: `intercept(req: HttpRequest<unknown>, next: HttpHandler) {\n  const token = localStorage.getItem('token');\n  return next.handle(req.clone({\n    setHeaders: token ? { Authorization: \`Bearer \${token}\` } : {}\n  }));\n}`, exercise: `Crie uma função que devolva true quando existir um token e false quando não existir.`, result: 'Sem token, a guarda redireciona para /login.' },
  quality: { minimum: `it('calcula total do carrinho', () => {\n  expect(calcularTotal([{ preco: 20, quantidade: 2 }])).toBe(40);\n});`, real: `@for (produto of produtos; track produto.id) {\n  <app-produto-card [produto]="produto" />\n}`, exercise: `Escreva um teste para uma função dobro que deve retornar 8 quando recebe 4.`, result: 'O teste passa quando o resultado real é igual ao resultado esperado.' },
  'final-project': { minimum: `const routes: Routes = [\n  { path: 'login', component: LoginComponent },\n  { path: 'dashboard', component: DashboardComponent, canActivate: [authGuard] },\n];`, real: `Dashboard\n├── resumo de pedidos\n├── tabela de usuários\n└── formulário de cadastro`, exercise: `Desenhe as páginas Login, Dashboard e Produtos. Para cada uma, escreva qual service e qual estado ela precisa.`, result: 'Depois do login, a pessoa navega para o dashboard protegido.' },
};
